In [2]:
import numpy as np

#сложение матриц

matrix1 = np.array([[1, 2, 4],
                    [7, 5, -2],
                    [-2, 1, 3]])
matrix2 = np.array([[-1, 0, 3],
                    [2, -6, 1],
                    [-7, 1, 5]])
print(matrix1 + matrix2)

[[ 0  2  7]
 [ 9 -1 -1]
 [-9  2  8]]


In [5]:
matrix1 = np.array([[0, 3, 4],
                    [-7, 1, -2],
                    [2, -1, 3]])
matrix2 = np.array([[1, 2, 4],
                    [7, 0, -2],
                    [-3, -2, 5]])
print(matrix1 + matrix2)

[[ 1  5  8]
 [ 0  1 -4]
 [-1 -3  8]]


In [10]:
#вычитание матриц

matrix1 = np.array([[5, 2, 9],
                    [7, 0, -2],
                    [-2, 8, 6]])
matrix2 = np.array([[1, -2, 1],
                    [7, 5, -2],
                    [-2, 1, 3]])
print(matrix2 - matrix1)

[[-4 -4 -8]
 [ 0  5  0]
 [ 0  7 -3]]


In [11]:
matrix1 = np.array([[1, -2, 8],
                    [7, 5, -2],
                    [-2, 3, 0]])
matrix2 = np.array([[0, 2, 4],
                    [1, -3, -2],
                    [-2, 1, 3]])
print(matrix2 - matrix1)

[[-1  4 -4]
 [-6 -8  0]
 [ 0 -2  3]]


In [13]:
# Умножение матриц

matrix1 = np.array([[1, 2, 4],
                    [7, 5, -2],
                    [-2, 1, 3]])
matrix2 = np.array([[-2, 3],
                    [4, 0],
                    [7, -1]])

result_matrix = np.dot(matrix1, matrix2)
print(result_matrix)

[[34 -1]
 [-8 23]
 [29 -9]]


In [14]:
matrix1 = np.array([[0, 3, 4],
                    [-7, 1, -2],
                    [2, -1, 3]])
matrix2 = np.array([[-3, 2],
                    [0, 4],
                    [-1, 7]])

result_matrix = np.dot(matrix1, matrix2)
print(result_matrix)

[[ -4  40]
 [ 23 -24]
 [ -9  21]]


In [15]:
matrix1 = np.array([[5, 2, 9],
                    [7, 0, -2],
                    [-2, 1, 6]])
matrix2 = np.array([[-2, 3],
                    [4, 5],
                    [0, -1]])

result_matrix = np.dot(matrix1, matrix2)
print(result_matrix)

[[ -2  16]
 [-14  23]
 [  8  -7]]


In [17]:
matrix1 = np.array([[1, -2, 8],
                    [7, 5, -2],
                    [-2, 3, 0]])
matrix2 = np.array([[-2, 3],
                    [4, 5],
                    [0, -1]])

result_matrix = np.dot(matrix1, matrix2)
print(result_matrix)

[[-10 -15]
 [  6  48]
 [ 16   9]]


In [18]:
matrix1 = np.array([[9, 2, 4],
                    [7, 5, -5],
                    [6, -2, 3]])
matrix2 = np.array([[-2, 0],
                    [4, 8],
                    [1, -1]])

result_matrix = np.dot(matrix1, matrix2)
print(result_matrix)

[[ -6  12]
 [  1  45]
 [-17 -19]]


In [21]:
matrix1 = np.array([[1, 2, 4],
                    [7, 5, -2],
                    [-2, 1, 3]])
matrix2 = np.array([[-1, 0, 3],
                    [2, -6, 1],
                    [-7, 1, 5]])
matrix3 = np.array([[-2, 3],
                    [4, 0],
                    [7, -1]])

inter_matrix = np.dot(matrix1, matrix2)
result_matrix = np.dot(inter_matrix, matrix3)
print(result_matrix)

[[ 193 -100]
 [ -50   35]
 [  92  -61]]


In [23]:
matrix1 = np.array([[0, 3, 4],
                    [-7, 1, -2],
                    [2, -1, 3]])
matrix2 = np.array([[1, 2, 4],
                    [7, 0, -2],
                    [-3, -2, 5]])
matrix3 = np.array([[-3, 2],
                    [0, 4],
                    [-1, 7]])

inter_matrix = np.dot(matrix1, matrix2)
result_matrix = np.dot(inter_matrix, matrix3)
print(result_matrix)

[[ -41   84]
 [  22 -308]
 [  17  139]]


In [24]:
matrix1 = np.array([[5, 2, 9],
                    [7, 0, -2],
                    [-2, 1, 6]])
matrix2 = np.array([[1, -2, 1],
                    [7, 5, -2],
                    [-2, 8, 3]])
matrix3 = np.array([[-2, 3],
                    [4, 5],
                    [0, -1]])

inter_matrix = np.dot(matrix1, matrix2)
result_matrix = np.dot(inter_matrix, matrix3)
print(result_matrix)

[[ 286  335]
 [-142 -118]
 [ 242  250]]


In [25]:
matrix1 = np.array([[1, -2, 8],
                    [7, 5, -2],
                    [-2, 3, 0]])
matrix2 = np.array([[0, 2, 4],
                    [1, -3, -2],
                    [-2, 1, 3]])
matrix3 = np.array([[0, 3],
                    [5, -4],
                    [7, -1]])

inter_matrix = np.dot(matrix1, matrix2)
result_matrix = np.dot(inter_matrix, matrix3)
print(result_matrix)

[[ 304 -150]
 [  69   27]
 [-163   75]]


In [26]:
matrix1 = np.array([[9, 2, 4],
                    [7, 5, -5],
                    [6, -2, 3]])
matrix2 = np.array([[8, 2, 4],
                    [0, 1, -3],
                    [-2, 1, 6]])
matrix3 = np.array([[-2, 0],
                    [4, 8],
                    [1, -1]])

inter_matrix = np.dot(matrix1, matrix2)
result_matrix = np.dot(inter_matrix, matrix3)
print(result_matrix)

[[ 22 138]
 [-93 129]
 [ 16  56]]


In [30]:
#обратная матрица

matrix = np.array([
    [1, 2, 4],
    [7, 5, -2],
    [-2, 1, 3]
])

matrix_inv = np.linalg.inv(matrix)

print(matrix_inv)

[[ 0.33333333 -0.03921569 -0.47058824]
 [-0.33333333  0.21568627  0.58823529]
 [ 0.33333333 -0.09803922 -0.17647059]]


In [31]:
matrix = np.array([
    [9, 2, 4],
    [7, 5, -5],
    [6, -2, 3]
])

matrix_inv = np.linalg.inv(matrix)

print(matrix_inv)

[[-0.02145923  0.06008584  0.12875536]
 [ 0.21888412 -0.01287554 -0.31330472]
 [ 0.1888412  -0.12875536 -0.13304721]]


In [32]:
matrix = np.array([
    [0, 3, 4],
    [-7, 1, -2],
    [2, -1, 3]
])

matrix_inv = np.linalg.inv(matrix)

print(matrix_inv)

[[ 0.01408451 -0.18309859 -0.14084507]
 [ 0.23943662 -0.11267606 -0.3943662 ]
 [ 0.07042254  0.08450704  0.29577465]]
